### PR TITLE
move core_msgs and frontend_utils

### PR DESCRIPTION
**Pull request by yunzc**
Since PointCloudMapper depends on core_msgs and frontend_utils, I think it should be moved to the common pkg. 
Let me know what you guys think. 
See https://github.com/NeBula-Autonomy/common_nebula_slam/pull/1

### CODE REVIEW

**Comment by BenjaminMorrell** [comment]
I am less up to speed on the different packages - so am happy for @femust to make the decision. I think we can eventually remove that package to be honest. 
Do you use it in LAMP at all @yunzc ?

**Comment by yunzc** [comment]
Yeah @BenjaminMorrell PointCloudMapper is also used in LAMP. So right now LOCUS is needed to compile LAMP, which is why I would like to move it to common_nebula_slam

**Comment by BenjaminMorrell** [comment]
Ah, we should definitely move it to common then.

**Review by BenjaminMorrell — APPROVED** [review]
Pending @femust reviews

**Review by femust — APPROVED** [review]

**Comment by femust** [comment]
ok let's merge this guys :)

**Pull request merged**
